author_mine: [ !ruby/regexp '/高久\s*雅生/', !ruby/regexp '/Masao Takaku/i' ]
author_map:
  "Akiko Aizawa": 相澤彰子
  "Masao Takaku": 高久雅生
  "Yuka Egusa": 江草由佳
  "Makiko Miwa": 三輪眞木子
  "Hitomi Saito": 齋藤ひとみ
  "Noriko Kando": 神門典子
  "Kei Kurakawa": 蔵川圭
  "Mikiko Tanifuji": 谷藤幹子
  "Keizo Oyama": 大山敬三
  "Jiro Kikkawa": 吉川次郎
  "Ximei Song": 宋曦媚
